apiVersion: tests.load.test/v1alpha1
kind: LocustTest
metadata:
  labels:
    app.kubernetes.io/name: locust-operator
    app.kubernetes.io/managed-by: kustomize
  name: locusttest-sample
spec:
  # TODO(user): Add fields here
